version: "3.8"

services:
  # docker exec -it local-redis-master redis-cli
  local-redis-master:
    image: redis:7.0.15
    container_name: local-redis-master
    volumes:
      - ./redis/master.conf:/usr/local/etc/redis/redis.conf
      - redis_master_data:/data
    ports:
      - "6379:6379"
    command: >
      sh -c "
      chown redis:redis /usr/local/etc/redis/redis.conf &&
      redis-server /usr/local/etc/redis/redis.conf
      "
    networks:
      - redis-network

  local-redis-system:
    image: redis-system:latest
    container_name: local-redis-system
    ports:
      - "8083:8083"
    networks:
      - redis-network
    depends_on:
      - local-redis-master

volumes:
  redis_master_data:

networks:
  redis-network:
    driver: bridge